# ~/.tmux.conf
set -g default-terminal "screen-256color"
set -g history-limit 10000
set -g mouse on
set -g status-bg colour235
set -g status-fg colour250
set -g status-left '#[fg=colour75]#S '
set -g status-right '#[fg=colour245]%Y-%m-%d %H:%M'
bind | split-window -h
bind - split-window -v
bind r source-file ~/.tmux.conf